-- 계층형 쿼리 (상-하 관계의 데이터를 조회할 때 사용한다.)
WITH RECURSIVE ECOLI_TREE(ID, PARENT_ID, DEPTH) AS(
    SELECT ID, PARENT_ID, 1
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, ET.DEPTH + 1
    FROM ECOLI_DATA E 
    INNER JOIN ECOLI_TREE ET ON E.PARENT_ID = ET.ID
)
SELECT ID
FROM ECOLI_TREE
WHERE DEPTH = 3
