SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS TOTAL_COUNT
     FROM ONLINE_SALE
     GROUP BY USER_ID, PRODUCT_ID
) SUMMARY
WHERE TOTAL_COUNT >= 2
ORDER BY USER_ID, PRODUCT_ID DESC