SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, 
       CAR_ID, 
       COUNT(CAR_ID) AS RECORD
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('20220801', 'YYYYMMDD') 
      AND START_DATE < TO_DATE('20221101', 'YYYYMMDD')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
AND START_DATE >= TO_DATE('20220801', 'YYYYMMDD') 
AND START_DATE < TO_DATE('20221101', 'YYYYMMDD')
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
ORDER BY MONTH, CAR_ID DESC;